### ISSUE TITLE
ath.c:193: _gcry_ath_mutex_lock: Assertion `*lock == ((ath_mutex_t) 0)' failed.

### ISSUE THREAD

**Issue by jmshelby** [SearchSpring/haus#20]
I'm getting this about 90% of the time on ubuntu (about 5% of the time on mac) - though not sure if that's the issue

```
jmshelby@hqpizza2:~/searchspring/haus-yaml$ haus
Cloning repo: toolsdev into /home/jmshelby/searchspring/haus-yaml/hauscfg/src/tools-dev
Cloning repo: smceast into /home/jmshelby/searchspring/haus-yaml/hauscfg/src/smc-east
Cloning repo: salukieast into /home/jmshelby/searchspring/haus-yaml/hauscfg/src/saluki-nodejs-east
Cloning repo: salukiindexereast into /home/jmshelby/searchspring/haus-yaml/hauscfg/src/saluki-indexer-east
Cloning repo: autocompleteeast into /home/jmshelby/searchspring/haus-yaml/hauscfg/src/autocomplete-east
Cloning repo: solreast into /home/jmshelby/searchspring/haus-yaml/hauscfg/src/solr_east
Cloning repo: salukinodejseast into /home/jmshelby/searchspring/haus-yaml/hauscfg/src/saluki-nodejs-east/src/searchspring-saluki
haus: ath.c:193: _gcry_ath_mutex_lock: Assertion `*lock == ((ath_mutex_t) 0)' failed.
SIGABRT: abort
PC=0x7f41d9212cc9
signal arrived during cgo execution

goroutine 12 [syscall, locked to thread]:
runtime.cgocall_errno(0x41d5df, 0xc2080995a8, 0x0)
    /usr/local/go/src/runtime/cgocall.go:130 +0xf5 fp=0xc208099588 sp=0xc208099560
gopkg.in/libgit2/git2go%2ev22._Cfunc_git_clone(0xc20804e058, 0x7f41c80008c0, 0x7f41c8019c40, 0xc208099608, 0xc200000000)
    /app/go/src/gopkg.in/libgit2/git2go.v22/:644 +0x43 fp=0xc2080995a8 sp=0xc208099588
gopkg.in/libgit2/git2go%2ev22.Clone(0xc20804c700, 0x3a, 0xc208056900, 0x5c, 0xc2080ba840, 0x0, 0x0, 0x0)
    /app/go/src/gopkg.in/libgit2/git2go.v22/clone.go:42 +0x1f4 fp=0xc208099728 sp=0xc2080995a8
github.com/SearchSpring/RepoTsar/gitutils.(*CloneInfo).CloneRepo(0xc2080ba800, 0xc208092568, 0x0, 0x0)
    /app/go/src/github.com/SearchSpring/RepoTsar/gitutils/clone.go:31 +0x228 fp=0xc2080997e8 sp=0xc208099728
github.com/SearchSpring/haus/app.(*Repo).CloneRepo(0xc2080ba7c0, 0xc2080924c0, 0x10, 0x0, 0x0)
    /app/go/src/github.com/SearchSpring/haus/app/repotsar.go:36 +0x280 fp=0xc208099890 sp=0xc2080997e8
github.com/SearchSpring/haus/app.(*Haus).createEnv(0xc208056600, 0xc20800a974, 0xb, 0xc20804e038, 0xc20803b0e0, 0xc208056660, 0x0, 0x0)
    /app/go/src/github.com/SearchSpring/haus/app/haus.go:119 +0xbce fp=0xc208099fa0 sp=0xc208099890
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc208099fa8 sp=0xc208099fa0
created by github.com/SearchSpring/haus/app.(*Haus).Run
    /app/go/src/github.com/SearchSpring/haus/app/haus.go:35 +0x202

goroutine 1 [chan receive]:
github.com/SearchSpring/haus/app.(*Haus).Run(0xc208056600, 0x0, 0x0)
    /app/go/src/github.com/SearchSpring/haus/app/haus.go:42 +0x289
main.main()
    /app/go/src/github.com/Searchspring/haus/main.go:67 +0x74b

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 5 [syscall, locked to thread]:
gopkg.in/libgit2/git2go%2ev22._Cfunc_git_clone(0xc20804e0f8, 0x7f41cc0008c0, 0x7f41cc0009f0, 0xc2080ad608, 0x0)
    /app/go/src/gopkg.in/libgit2/git2go.v22/:644 +0x43
gopkg.in/libgit2/git2go%2ev22.Clone(0xc208050190, 0x42, 0xc20804c180, 0x3b, 0xc20804c880, 0x0, 0x0, 0x0)
    /app/go/src/gopkg.in/libgit2/git2go.v22/clone.go:42 +0x1f4
github.com/SearchSpring/RepoTsar/gitutils.(*CloneInfo).CloneRepo(0xc20804c800, 0xc2080924d0, 0x0, 0x0)
    /app/go/src/github.com/SearchSpring/RepoTsar/gitutils/clone.go:31 +0x228
github.com/SearchSpring/haus/app.(*Repo).CloneRepo(0xc20804c7c0, 0xc208092500, 0x8, 0x0, 0x0)
    /app/go/src/github.com/SearchSpring/haus/app/repotsar.go:36 +0x280
github.com/SearchSpring/haus/app.(*Haus).createEnv(0xc208056600, 0xc20800a5b6, 0x9, 0xc20804e038, 0xc20803b0e0, 0xc208056660, 0x0, 0x0)
    /app/go/src/github.com/SearchSpring/haus/app/haus.go:102 +0x878
created by github.com/SearchSpring/haus/app.(*Haus).Run
    /app/go/src/github.com/SearchSpring/haus/app/haus.go:35 +0x202

goroutine 10 [syscall, locked to thread]:
gopkg.in/libgit2/git2go%2ev22._Cfunc_git_clone(0xc20804e1c0, 0x7f41c40009f0, 0x7f41c40008c0, 0xc2080bf608, 0xc200000000)
    /app/go/src/gopkg.in/libgit2/git2go.v22/:644 +0x43
gopkg.in/libgit2/git2go%2ev22.Clone(0xc20804cf00, 0x33, 0xc20804cf80, 0x3a, 0xc20804d800, 0x0, 0x0, 0x0)
    /app/go/src/gopkg.in/libgit2/git2go.v22/clone.go:42 +0x1f4
github.com/SearchSpring/RepoTsar/gitutils.(*CloneInfo).CloneRepo(0xc20804d7c0, 0xc208093028, 0x0, 0x0)
    /app/go/src/github.com/SearchSpring/RepoTsar/gitutils/clone.go:31 +0x228
github.com/SearchSpring/haus/app.(*Repo).CloneRepo(0xc20804d780, 0xc2080930d6, 0x7, 0x0, 0x0)
    /app/go/src/github.com/SearchSpring/haus/app/repotsar.go:36 +0x280
github.com/SearchSpring/haus/app.(*Haus).createEnv(0xc208056600, 0xc20800a6e0, 0x8, 0xc20804e038, 0xc20803b0e0, 0xc208056660, 0x0, 0x0)
    /app/go/src/github.com/SearchSpring/haus/app/haus.go:102 +0x878
created by github.com/SearchSpring/haus/app.(*Haus).Run
    /app/go/src/github.com/SearchSpring/haus/app/haus.go:35 +0x202

goroutine 25 [syscall, locked to thread]:
gopkg.in/libgit2/git2go%2ev22._Cfunc_git_clone(0xc20804e060, 0x7f41c00008c0, 0x7f41c00009f0, 0xc2080eb608, 0xc200000000)
    /app/go/src/gopkg.in/libgit2/git2go.v22/:644 +0x43
gopkg.in/libgit2/git2go%2ev22.Clone(0xc20804dd40, 0x3c, 0xc2080517c0, 0x43, 0xc20804c6c0, 0x0, 0x0, 0x0)
    /app/go/src/gopkg.in/libgit2/git2go.v22/clone.go:42 +0x1f4
github.com/SearchSpring/RepoTsar/gitutils.(*CloneInfo).CloneRepo(0xc20804c600, 0xc208093c50, 0x0, 0x0)
    /app/go/src/github.com/SearchSpring/RepoTsar/gitutils/clone.go:31 +0x228
github.com/SearchSpring/haus/app.(*Repo).CloneRepo(0xc20804c500, 0xc208093ce0, 0x10, 0x0, 0x0)
    /app/go/src/github.com/SearchSpring/haus/app/repotsar.go:36 +0x280
github.com/SearchSpring/haus/app.(*Haus).createEnv(0xc208056600, 0xc20801f020, 0x11, 0xc20804e038, 0xc20803b0e0, 0xc208056660, 0x0, 0x0)
    /app/go/src/github.com/SearchSpring/haus/app/haus.go:102 +0x878
created by github.com/SearchSpring/haus/app.(*Haus).Run
    /app/go/src/github.com/SearchSpring/haus/app/haus.go:35 +0x202

goroutine 23 [syscall, locked to thread]:
gopkg.in/libgit2/git2go%2ev22._Cfunc_git_clone(0xc20804e098, 0x7f41bc0008c0, 0x7f41bc0009f0, 0xc2080d5608, 0xc200000000)
    /app/go/src/gopkg.in/libgit2/git2go.v22/:644 +0x43
gopkg.in/libgit2/git2go%2ev22.Clone(0xc20804ca00, 0x3e, 0xc208050640, 0x45, 0xc20804d640, 0x0, 0x0, 0x0)
    /app/go/src/gopkg.in/libgit2/git2go.v22/clone.go:42 +0x1f4
github.com/SearchSpring/RepoTsar/gitutils.(*CloneInfo).CloneRepo(0xc20804d600, 0xc208092830, 0x0, 0x0)
    /app/go/src/github.com/SearchSpring/RepoTsar/gitutils/clone.go:31 +0x228
github.com/SearchSpring/haus/app.(*Repo).CloneRepo(0xc20804d5c0, 0xc20801ea40, 0x11, 0x0, 0x0)
    /app/go/src/github.com/SearchSpring/haus/app/repotsar.go:36 +0x280
github.com/SearchSpring/haus/app.(*Haus).createEnv(0xc208056600, 0xc20801ec60, 0x12, 0xc20804e038, 0xc20803b0e0, 0xc208056660, 0x0, 0x0)
    /app/go/src/github.com/SearchSpring/haus/app/haus.go:102 +0x878
created by github.com/SearchSpring/haus/app.(*Haus).Run
    /app/go/src/github.com/SearchSpring/haus/app/haus.go:35 +0x202

goroutine 29 [syscall, locked to thread]:
gopkg.in/libgit2/git2go%2ev22._Cfunc_git_clone(0xc20804e030, 0x7f41b40008c0, 0x7f41b40009f0, 0xc2080db608, 0xc200000000)
    /app/go/src/gopkg.in/libgit2/git2go.v22/:644 +0x43
gopkg.in/libgit2/git2go%2ev22.Clone(0xc2080ba100, 0x3c, 0xc2080ba180, 0x3b, 0xc2080ba400, 0x0, 0x0, 0x0)
    /app/go/src/gopkg.in/libgit2/git2go.v22/clone.go:42 +0x1f4
github.com/SearchSpring/RepoTsar/gitutils.(*CloneInfo).CloneRepo(0xc2080ba340, 0xc208093d98, 0x0, 0x0)
    /app/go/src/github.com/SearchSpring/RepoTsar/gitutils/clone.go:31 +0x228
github.com/SearchSpring/haus/app.(*Repo).CloneRepo(0xc2080ba300, 0xc208093e60, 0x8, 0x0, 0x0)
    /app/go/src/github.com/SearchSpring/haus/app/repotsar.go:36 +0x280
github.com/SearchSpring/haus/app.(*Haus).createEnv(0xc208056600, 0xc20800a7c0, 0x9, 0xc20804e038, 0xc20803b0e0, 0xc208056660, 0x0, 0x0)
    /app/go/src/github.com/SearchSpring/haus/app/haus.go:102 +0x878
created by github.com/SearchSpring/haus/app.(*Haus).Run
    /app/go/src/github.com/SearchSpring/haus/app/haus.go:35 +0x202

rax     0x0
rbx     0x7f41dad46000
rcx     0xffffffffffffffff
rdx     0x6
rdi     0xa30
rsi     0xa34
rbp     0x7f41d935c830
rsp     0x7f41d2ffc388
r8      0xfefefefefefefe00
r9      0x7f41c801a940
r10     0x8
r11     0x206
r12     0x7f41d8fb3246
r13     0x7f41d8fb32a0
r14     0x7f41d2ffc5f8
r15     0x0
rip     0x7f41d9212cc9
rflags  0x206
cs      0x33
fs      0x0
gs      0x0

```

**Comment by ghellings** [comment]
With any haus yaml, or a specific one?

**Comment by jmshelby** [comment]
Well i've only been using the one from the 'automated' branch - so not sure about the other ones
 BTW - I kept getting error messages about missing c/c++ libraries, but got around them by installing those libraries manually with aptitude

**Comment by jmshelby** [comment]
Also - i'm using the .deb package of v0.1.4 - since there wasn't a bin for for 0.1.5, and I was assuming that there wasn't any changes from 0.1.4-0.1.5 but I could be wrong

**Comment by jmshelby** [comment]
does your new v0.1.6 resolve these issues for ubuntu by chance?

**Comment by ghellings** [comment]
I believe I've tracked this issue down to a race condition in the version of libgit2 I was compiling against.  I've upgrade to a later version, and I believe the problem is resolved.

**Comment by jmshelby** [comment]
I'm still getting this with the latest release BTW (0.1.7)

**Comment by ghellings** [comment]
Ok, do you know if the libssh2 on your machine was compiled against openssl or libgcrypt ?  I believe the issue is still openssl, but because I didn't manage to get libssh2 to statically compile in, it's openssl via libssh2.

**Comment by jmshelby** [comment]
interesting - i thought go always compiled everything statically ... Is it just because these are c libs that you were able to dynamically link them?

I'll have to check which source libssh2 is coming from - standby

**Comment by ghellings** [comment]
Yeah, it's because it's a c lib.  There are options to pass ldflags to statically compile, but that raises a whole different issue on OS X due to libcrt0 not being statically compiled on OS X.  I'm thinking of replacing git2go with https://github.com/src-d/go-git which is a pure go implementation.

**Comment by jmshelby** [comment]
Would it be better to just rely on a container distribution?
